SELECT
  "SPRIDEN_LAST_NAME",
  "SSBSECT_SUBJ_CODE",
  "SSBSECT_CRSE_NUMB",
  "Weekday",
  "SSBSECT_CAMP_CODE",
  "SSRMEET_BLDG_CODE",
  "SSRMEET_ROOM_CODE",
  "SSBSECT_SEQ_NUMB",
  "SSBSECT_ENRL",
  "SSRMEET_BEGIN_TIME",
  "SSRMEET_END_TIME",
  "SSBSECT_SSTS_CODE",
  "SSBSECT_PTRM_CODE",
  "SIRASGN_PRIMARY_IND"
FROM (
  SELECT
    "q01".*,
    ROW_NUMBER() OVER (PARTITION BY "SSBSECT_SUBJ_CODE", "SSBSECT_CRSE_NUMB", "SSBSECT_CAMP_CODE", "SSRMEET_BLDG_CODE", "SPRIDEN_LAST_NAME" ORDER BY SSBsect_SUBJ_CODE) AS "col01" --ADDED ORDER BY INSIDE PARATHESIS
  FROM (
    SELECT
      "SPRIDEN_LAST_NAME",
      "SSBSECT_SUBJ_CODE",
      "SSBSECT_CRSE_NUMB",
      "SSRMEET_MON_DAY" || "SSRMEET_TUE_DAY" || "SSRMEET_WED_DAY" || "SSRMEET_THU_DAY" || "SSRMEET_FRI_DAY" || "SSRMEET_SAT_DAY" AS "Weekday",
      "SSBSECT_CAMP_CODE",
      "SSRMEET_BLDG_CODE",
      "SSRMEET_ROOM_CODE",
      "SSBSECT_SEQ_NUMB",
      "SSBSECT_ENRL",
      "SSRMEET_BEGIN_TIME",
      "SSRMEET_END_TIME",
      "SSBSECT_SSTS_CODE",
      "SSBSECT_PTRM_CODE",
      "SIRASGN_PRIMARY_IND"
    FROM (
SELECT DISTINCT *

           FROM SSBSECT,SSRMEET,
           SPRIDEN,SIRASGN

           WHERE SSBSECT_TERM_CODE=SSRMEET_TERM_CODE
           AND SSBSECT_CRN=SSRMEET_CRN
           AND SPRIDEN_PIDM=SIRASGN_PIDM
           AND SIRASGN_CRN=SSBSECT_CRN
           AND SIRASGN_TERM_CODE = SSBSECT_TERM_CODE
           AND SPRIDEN_CHANGE_IND IS NULL

    ) "q01"
    WHERE
      ("SSBSECT_TERM_CODE" = 202320.0 AND "SSBSECT_SSTS_CODE" != 'C' AND "SSBSECT_CAMP_CODE" != 'H' AND "SSBSECT_SEQ_NUMB" != '100' AND "SSBSECT_PTRM_CODE" != '5M1' AND "SSBSECT_PTRM_CODE" != '8M1' AND "SIRASGN_PRIMARY_IND" = 'Y') AND
      (NOT(SUBSTR("SSBSECT_SEQ_NUMB", 1, 1) IN ('D', 'P', 'Z')))
  ) "q01"
) "q01"
WHERE ("col01" = 1)