SELECT DISTINCT SSBSECT_TERM_CODE,SSBSECT_CRN,SSBSECT_SUBJ_CODE || '-' || SSBSECT_CRSE_NUMB AS "SUBJ_COURSE",SSBSECT_SEQ_NUMB,
SSRMEET_MON_DAY,SSRMEET_TUE_DAY,"SSRMEET_WED_DAY", "SSRMEET_THU_DAY", "SSRMEET_FRI_DAY","SSRMEET_SAT_DAY",SSRMEET_SUN_DAY,
TO_CHAR(TO_DATE(SSRMEET_BEGIN_TIME,'HH24MI'),'HH:MI AM') AS START_TIME,
TO_CHAR(TO_DATE(SSRMEET_END_TIME,'HH24MI'),'HH:MI AM') AS END_TIME,


/*
SSRMEET_BLDG_CODE,SSRMEET_ROOM_CODE,SSBSECT_SUBJ_CODE,SSBSECT_CRSE_NUMB,
SSBSECT_SEQ_NUMB,SSBSECT_ENRL,SSRMEET_BEGIN_TIME,SSRMEET_END_TIME
*/


(SELECT DISTINCT STVCOLL_DESC FROM STVCOLL S2
   WHERE S2.STVCOLL_CODE = SCBCRSE.SCBCRSE_COLL_CODE) AS SCHOOL,
   
  (SELECT DISTINCT STVDEPT_DESC FROM STVDEPT S2
   WHERE S2.STVDEPT_CODE = SCBCRSE.SCBCRSE_DEPT_CODE) AS DEPARTMENT,
  
  (SELECT DISTINCT STVCAMP_DESC FROM STVCAMP S2
   WHERE S2.STVCAMP_CODE = SSBSECT.SSBSECT_CAMP_CODE) AS CAMPUS,
   
  (SELECT DISTINCT STVTERM_DESC FROM STVTERM S2
   WHERE S2.STVTERM_CODE = SSBSECT.SSBSECT_TERM_CODE) AS TERM 

FROM SSBSECT,SCBCRSE, SSRMEET--,STVCOLL,STVDEPT,STVCAMP,STVTERM

WHERE SSBSECT_SUBJ_CODE = SCBCRSE_SUBJ_CODE
AND SSBSECT_CRSE_NUMB = SCBCRSE_CRSE_NUMB
AND SSBSECT_CRN = SSRMEET_CRN
AND SSBSECT_TERM_CODE = SSRMEET_TERM_CODE

/* AND STVCOLL_CODE =SCBCRSE_COLL_CODE
AND STVDEPT_CODE = SCBCRSE_DEPT_CODE
AND STVCAMP_CODE = SSBSECT_CAMP_CODE
AND STVTERM_CODE = SSBSECT_TERM_CODE */

AND SCBCRSE_EFF_TERM = (SELECT MAX(A.SCBCRSE_EFF_TERM)
                          FROM SCBCRSE A
                          WHERE A.SCBCRSE_SUBJ_CODE = SSBSECT_SUBJ_CODE
                          AND A.SCBCRSE_CRSE_NUMB = SSBSECT_CRSE_NUMB)
     
                   
/*AND SSBSECT_TERM_CODE <= 202430
and SSBSECT_TERM_CODE >= 201910 */

AND SSBSECT_TERM_CODE IN (201910,201920,201930,202010,202020,202030,202110,202120,202120,202210,202220,202230
  ,202310,202320,202330,202410,202420,202430,202510,202520,202530)