SELECT DISTINCT 
  "SSBSECT_CRN" CRN,
  "SSBSECT_TERM_CODE" TERM,
  SCBCRSE_COLL_CODE SCHOOL,
  "SSBSECT_SUBJ_CODE" COURSE,
  "SSBSECT_CRSE_NUMB" COURSE_NUMBER,
  "SSBSECT_SEQ_NUMB" SEQUENCE_NUMBER,
  
  COUNT(*) AS "Count"
FROM (
  SELECT
    "SSBSECT_CRN",
    "SSBSECT_TERM_CODE",
    "SSBSECT_SUBJ_CODE",
    "SSBSECT_CRSE_NUMB",
    "SSBSECT_SEQ_NUMB",
    SCBCRSE_COLL_CODE
  FROM (
    SELECT
    SCBCRSE_COLL_CODE,
      "SSBSECT_CRN",
      "SSBSECT_TERM_CODE",
      "SSBSECT_SUBJ_CODE",
      "SSBSECT_CRSE_NUMB",
      "SSBSECT_SEQ_NUMB",
      
      ROW_NUMBER() OVER (PARTITION BY "SSBSECT_TERM_CODE",SCBCRSE_COLL_CODE,"SSBSECT_SUBJ_CODE", "SSBSECT_CRSE_NUMB", "SSBSECT_SEQ_NUMB",SCBCRSE_COLL_CODE ORDER BY "SSBSECT_TERM_CODE", "SSBSECT_SUBJ_CODE", "SSBSECT_CRSE_NUMB") AS "col01"
    FROM (
 
 
SELECT DISTINCT *
 
FROM SSBSECT,SCBCRSE
 
where SSBSECT_SSTS_CODE != 'C'

AND SCBCRSE_SUBJ_CODE=SSBSECT_SUBJ_CODE
AND SCBCRSE_CRSE_NUMB=SSBSECT_CRSE_NUMB
 
 
    ) "q01"
    WHERE ("SSBSECT_TERM_CODE" >= 201910.0 AND "SSBSECT_TERM_CODE" <= 202330.0)
  ) "q01"
  WHERE ("col01" = 1)
) "q01"
GROUP BY
  "SSBSECT_CRN",
  "SSBSECT_TERM_CODE",
  "SSBSECT_SUBJ_CODE",
  "SSBSECT_CRSE_NUMB",
  "SSBSECT_SEQ_NUMB",
  SCBCRSE_COLL_CODE