
SELECT DISTINCT SSBSECT_TERM_CODE,SSBSECT_CRN,SSBSECT_SUBJ_CODE || '-' || SSBSECT_CRSE_NUMB AS "SUBJ_COURSE",SSBSECT_SEQ_NUMB,
NVL(SSRMEET_MON_DAY,'NONE') AS MONDAY,
NVL(SSRMEET_TUE_DAY,'NONE') AS TUESDAY,
NVL(SSRMEET_WED_DAY,'NONE') AS WEDNESDAY,
NVL(SSRMEET_THU_DAY,'NONE') AS THURSDAY,
NVL(SSRMEET_FRI_DAY,'NONE') AS FRIDAY,
NVL(SSRMEET_SAT_DAY,'NONE') AS SATURDAY,
NVL(SSRMEET_SUN_DAY,'NONE') AS SUNDAY,
NVL(TO_CHAR(TO_DATE(SSRMEET_BEGIN_TIME,'HH24MI'),'HH:MI AM'),'NONE') AS START_TIME,
NVL(TO_CHAR(TO_DATE(SSRMEET_END_TIME,'HH24MI'),'HH:MI AM'),'NONE') AS END_TIME,
STVCOLL_DESC AS SCHOOL,STVDEPT_DESC AS DEPARTMENT,STVCAMP_CODE AS CAMPUS,STVTERM_DESC AS TERM,
NVL(SSRMEET_MON_DAY || SSRMEET_TUE_DAY || SSRMEET_WED_DAY || SSRMEET_THU_DAY || SSRMEET_FRI_DAY ||
SSRMEET_SAT_DAY ||SSRMEET_SUN_DAY,'NONE') AS WEEKDAY


FROM SSBSECT
JOIN SCBCRSE 
  ON SSBSECT_SUBJ_CODE = SCBCRSE_SUBJ_CODE
  AND SSBSECT_CRSE_NUMB = SCBCRSE_CRSE_NUMB
JOIN SSRMEET 
  ON SSBSECT_CRN = SSRMEET_CRN
  AND SSBSECT_TERM_CODE = SSRMEET_TERM_CODE

JOIN STVCOLL 
  ON STVCOLL_CODE = SCBCRSE_COLL_CODE
JOIN STVDEPT 
  ON STVDEPT_CODE = SCBCRSE_DEPT_CODE
JOIN STVCAMP 
  ON STVCAMP_CODE = SSBSECT_CAMP_CODE
JOIN STVTERM 
  ON STVTERM_CODE = SSBSECT_TERM_CODE

WHERE SCBCRSE_EFF_TERM = (SELECT MAX(A.SCBCRSE_EFF_TERM)
                          FROM SCBCRSE A
                          WHERE A.SCBCRSE_SUBJ_CODE = SSBSECT_SUBJ_CODE
                          AND A.SCBCRSE_CRSE_NUMB = SSBSECT_CRSE_NUMB)

AND SSBSECT_TERM_CODE IN (201910,201920,201930,202010,202020,202030,202110,202120,202120,202210,202220,202230
,202310,202320,202330,202410,202420,202430,202510,202520,202530)
