SELECT count(distinct ssbsect_crn)
 
FROM SSBSECT
 
WHERE SSBSECT_TERM_CODE = 202320
  AND SUBSTR(SSBSECT_SEQ_NUMB,1,1) NOT IN('D','Z','P')
  AND SSBSECT_CAMP_CODE != 'H'
  AND SSBSECT_SEQ_NUMB != '100'
  AND SSBSECT_PTRM_CODE NOT IN('5M1','8M1')